// This file is auto-generated by @hey-api/openapi-ts

export type BodyCreateEpisodeEpisodesPost = {
    episode: EpisodeCreate;
    files: Array<Blob | File>;
};

export type Episode = {
    uuid?: string;
    preprocessed?: boolean;
    postprocessed?: boolean;
    editor_state?: string;
    title?: string;
    created_at?: string;
};

export type EpisodeCreate = {
    title: string;
    editor_state?: string | null;
    preprocessed?: boolean | null;
    postprocessed?: boolean | null;
};

export type EpisodeUpdate = {
    title?: string | null;
    editor_state?: string | null;
    preprocessed?: boolean | null;
    postprocessed?: boolean | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ReadEpisodesEpisodesGetData = {
    body?: never;
    path?: never;
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/episodes/';
};

export type ReadEpisodesEpisodesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEpisodesEpisodesGetError = ReadEpisodesEpisodesGetErrors[keyof ReadEpisodesEpisodesGetErrors];

export type ReadEpisodesEpisodesGetResponses = {
    /**
     * Successful Response
     */
    200: Array<Episode>;
};

export type ReadEpisodesEpisodesGetResponse = ReadEpisodesEpisodesGetResponses[keyof ReadEpisodesEpisodesGetResponses];

export type CreateEpisodeEpisodesPostData = {
    body: BodyCreateEpisodeEpisodesPost;
    path?: never;
    query?: never;
    url: '/episodes/';
};

export type CreateEpisodeEpisodesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEpisodeEpisodesPostError = CreateEpisodeEpisodesPostErrors[keyof CreateEpisodeEpisodesPostErrors];

export type CreateEpisodeEpisodesPostResponses = {
    /**
     * Successful Response
     */
    201: Episode;
};

export type CreateEpisodeEpisodesPostResponse = CreateEpisodeEpisodesPostResponses[keyof CreateEpisodeEpisodesPostResponses];

export type DeleteEpisodeEpisodesEpisodeUuidDeleteData = {
    body?: never;
    path: {
        episode_uuid: string;
    };
    query?: never;
    url: '/episodes/{episode_uuid}';
};

export type DeleteEpisodeEpisodesEpisodeUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEpisodeEpisodesEpisodeUuidDeleteError = DeleteEpisodeEpisodesEpisodeUuidDeleteErrors[keyof DeleteEpisodeEpisodesEpisodeUuidDeleteErrors];

export type DeleteEpisodeEpisodesEpisodeUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteEpisodeEpisodesEpisodeUuidDeleteResponse = DeleteEpisodeEpisodesEpisodeUuidDeleteResponses[keyof DeleteEpisodeEpisodesEpisodeUuidDeleteResponses];

export type ReadEpisodeEpisodesEpisodeUuidGetData = {
    body?: never;
    path: {
        episode_uuid: string;
    };
    query?: never;
    url: '/episodes/{episode_uuid}';
};

export type ReadEpisodeEpisodesEpisodeUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEpisodeEpisodesEpisodeUuidGetError = ReadEpisodeEpisodesEpisodeUuidGetErrors[keyof ReadEpisodeEpisodesEpisodeUuidGetErrors];

export type ReadEpisodeEpisodesEpisodeUuidGetResponses = {
    /**
     * Successful Response
     */
    200: Episode;
};

export type ReadEpisodeEpisodesEpisodeUuidGetResponse = ReadEpisodeEpisodesEpisodeUuidGetResponses[keyof ReadEpisodeEpisodesEpisodeUuidGetResponses];

export type UpdateEpisodeEpisodesEpisodeUuidPatchData = {
    body: EpisodeUpdate;
    path: {
        episode_uuid: string;
    };
    query?: never;
    url: '/episodes/{episode_uuid}';
};

export type UpdateEpisodeEpisodesEpisodeUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEpisodeEpisodesEpisodeUuidPatchError = UpdateEpisodeEpisodesEpisodeUuidPatchErrors[keyof UpdateEpisodeEpisodesEpisodeUuidPatchErrors];

export type UpdateEpisodeEpisodesEpisodeUuidPatchResponses = {
    /**
     * Successful Response
     */
    200: Episode;
};

export type UpdateEpisodeEpisodesEpisodeUuidPatchResponse = UpdateEpisodeEpisodesEpisodeUuidPatchResponses[keyof UpdateEpisodeEpisodesEpisodeUuidPatchResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};